Marks qgrid as broken due to failing post-link script
```ERROR conda.core.link:_execute(701): An error occurred while installing package 'conda-forge::qgrid-1.3.1-pyhd8ed1ab_3'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::qgrid-1.3.1-pyhd8ed1ab_3
location of failed script: /home/afullard/.conda/envs/tardis2/bin/.qgrid-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: 
stderr: 
return code: 1```